[profile.default]
optimizer = false
solc_version = "0.8.21"

remappings = [
  "@oasisprotocol/sapphire-contracts/contracts=lib/sapphire-paratime/contracts/contracts",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "escrin/=lib/escrin/evm/src"
]

[rpc_endpoints]
hardhat = "http://127.0.0.1:8545"
localhost8546 = "http://127.0.0.1:8546"
sapphire-testnet = "https://testnet.sapphire.oasis.dev"
sapphire-mainnet = "https://sapphire.oasis.io"
emerald-testnet = "https://testnet.emerald.oasis.dev"
emerald-mainnet = "https://emerald.oasis.io"

[fmt]
line_length = 100

[profile.release]
optimizer = true
optimizer_runs = 30_000
via_ir = true
