[profile.default]
solc_version = "0.8.19"
optimizer_runs = 30_000
via_ir = true

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
  "escrin/=lib/escrin/evm/contracts"
]

[rpc_endpoints]
sapphire-testnet = "https://testnet.sapphire.oasis.dev"
sapphire-mainnet = "https://sapphire.oasis.io"
emerald-testnet = "https://testnet.emerald.oasis.dev"
emerald-mainnet = "https://emerald.oasis.io"

[fmt]
line_length = 100
