[profile.default]
solc_version = "0.8.19"
optimizer_runs = 30_000
via_ir = true
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib', '../node_modules']
test = 'test'
cache_path  = 'forge-cache'

[rpc_endpoints]
sapphire-testnet = "https://testnet.sapphire.oasis.dev"
sapphire-mainnet = "https://sapphire.oasis.io"
emerald-testnet = "https://testnet.emerald.oasis.dev"
emerald-mainnet = "https://emerald.oasis.io"

[fmt]
line_length = 100
